---
DataConfig:
  dataset: "Office31"

ModelConfig:
  backbone: "resnet50"
  channels_per_group: 0
  pretrain_strategy: "Gsfda"
  bottleneck_dim: 256

TrainingConfig:
  batch_size: 64
  # The total data numbers we use in each epoch
  epoch_samples: 2048
  total_epochs: 20
  # optimizer
  optimizer: "SGD"
  momentum: 0.9
  # regularization
  weight_decay: 0.0005
  # We decay learning rate from begin value to end value with cosine annealing schedule
  learning_rate_begin: 0.001
  learning_rate_end: 0.0002
  # We use EMA to retain the accuracy in source domain
  ema: False

DAConfig:
  source_domain: "amazon"
  target_domain: "webcam"
  method: "Gsfda"

GsfdaConfig:
  epsilon: 0.00001
  gen_par: 1
  k: 2 # k for knn cluster
  no_embedding: False
  diff_lr: True

DataAugConfig:
  method: "identity" # method can be "identity", "edgemix"










