---
DataConfig:
  dataset: "OfficeHome"

ModelConfig:
  backbone: "resnet50"
  channels_per_group: 0
  pretrain_strategy: "shot"
  bottleneck_dim: 256

TrainingConfig:
  batch_size: 64
  # The total data numbers we use in each epoch
  epoch_samples: 2048
  total_epochs: 20
  # optimizer
  optimizer: "SGD"
  momentum: 0.9
  # regularization
  weight_decay: 0.0005
  # We decay learning rate from begin value to end value with cosine annealing schedule
  learning_rate_begin: 0.002
  learning_rate_end: 0.001
  # We use EMA to retain the accuracy in source domain
  ema: True
  tao_begin: 0.8
  tao_end: 0.95

DAConfig:
  source_domain: "Clipart"
  target_domain: "Art"
  method: "CoSDA+AaD"

AaDConfig: # batch_size: 64 is proper
  k: 2
  alpha: 0.4 # the param lambda in the paper.
  gamma: 0.96
  ema: False

DistillConfig:
  mixup: True
  beta: 0.1

DataAugConfig:
  method: "identity" # method can be "identity", "edgemix"