---
DataConfig:
  dataset: "DomainNet_mini"

ModelConfig:
  backbone: "resnet50"
  channels_per_group: 0
  pretrain_strategy: "shot"
  bottleneck_dim: 512

TrainingConfig:
  batch_size: 256
  # The total data numbers we use in each epoch
  epoch_samples: 30000
  total_epochs: 10
  # optimizer
  optimizer: "SGD"
  momentum: 0.9
  # regularization
  weight_decay: 0.0005
  # We decay learning rate from begin value to end value with cosine annealing schedule
  learning_rate_begin: 0.0005
  learning_rate_end: 0.0001
  ema: True
  tao_begin: 0.95
  tao_end: 0.99

DAConfig:
  source_domain: "painting"
  target_domain: "sketch"
  method: "CoTTA"

CoTTAConfig:
  aug_times: 32
  rst: 0.01
  ap: 0.92
  confidence_gate_begin: 0.2
  confidence_gate_end: 0.4

DataAugConfig:
  method: "identity" # method can be "identity", "edgemix"










