---
DataConfig:
  dataset: "Office31"
  absent_domain: ""

ModelConfig:
  backbone: "resnet50"
  channels_per_group: 0
  bottleneck_dim: 256

TrainingConfig:
  batch_size: 64
  # The total data numbers we use in each epoch
  epoch_samples: 2048
  total_epochs: 20
  # We decay learning rate from begin value to end value with cosine annealing schedule
  learning_rate_begin: 0.01
  learning_rate_end: 0.0002
  # optimizer
  optimizer: "SGD"
  momentum: 0.9
  # regularization
  weight_decay: 0.0005
  method: "shot++"





